# -*- coding: utf-8 -*-
"""2021-08-29-prey-predator.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1b4yIihtODKNF2lOg-HSEvISzoyuWivjR
"""

import numpy as np
from scipy.integrate import solve_ivp
import matplotlib.pyplot as plt
a=1;b=1;c=1;d=1;
def ppsys(t,y):
  return [a*y[0]-b*y[0]*y[1],-c*y[1]+d*y[0]*y[1]]

# Prey-Predator (Lotka-Voltera) 微分方程式の数値解. y[0] ねずみ, y[1] 猫
sol = solve_ivp(ppsys,[0,10],[4,1],method="RK45",dense_output="True")
t=np.linspace(0,10,100)
z = sol.sol(t)
plt.gca().clear()
plt.plot(t,z[1].T)
# コマンドラインでの実行用.
plt.show()

from scipy.optimize import least_squares
# sum_j (a(j).x - b(j))^2 を最小化する vector x を求めたい.
def lfunc(x,a,b):
    n = len(a)
    s=np.array([np.dot(x,a[i])-b[i] for i in range(n)])
    return s
size=10
t2=np.linspace(0,10,size)
x2=sol.sol(t2)
xx=x2[0]
yy=x2[1]
print(a,b,c,d)
xx1=a*xx-b*xx*yy
yy1=-c*yy+d*xx*yy
yy2=-c*yy1+d*xx1*yy+d*xx*yy1
# yy, yy1, yy2 は t2 時間における y, y', y'' 猫
print(yy);print(yy1);print(yy2)
aa=np.array([yy**2*yy1,-yy*yy1,yy**3,-yy**2]).T
bb=(yy1**2-yy*yy2).T
print(aa); print(bb)

x0=np.zeros(4)
res_1=least_squares(lfunc,x0,args=[aa,bb])
Res_1=res_1
print('res_1.x=',res_1.x)
print('res_1.cost(loss functionの値)=',res_1.cost*2)
print('res_1.optimality=',res_1.optimality)
pp=res_1.x
print(pp[0]*pp[3]-pp[1]*pp[2], 'is zero?')
# b=pp[0], a=pp[1],c=pp[2]/b とパラメータがきまる.